### ISSUE TITLE
Rename to chimera-apogee

### ISSUE THREAD

**Issue by phsilva** [astroufsc/chimera-apogee#1]
I think we already agreed on that. Any problem to rename it?

**Comment by wschoenell** [comment]
I think that this plugin never will be used as it is designed right now. It is a program in C which grabs the image, do the WCS and so on and save all on a fits file, including the header. The only Python interaction here is to basically a call (which does not work, btw) to the main function on C++ side and do everything. We can change the name, but put a big warning saying that this plugin does not works at all!

**Comment by phsilva** [comment]
Hum, can't we add a ctypes interface to whatever code the C++ main function is calling and then integrate it like the chimera-sbig driver?

**Comment by phsilva** [comment]
but rename it anyway, I think. then we can think on what to do about it.

**Comment by wschoenell** [comment]
Ok. Done.

I think that we can get rid of ALL C++ code here and access the manufacturer's library (.so, .dll) directly from Python via CTYPES like we did on SBIG. As far as I remember, the lib here is even more high level that the SBIG's.

**Comment by wschoenell** [comment]
Added a warning of not-working plugin on 6012a7d3989a7265649b6b3af3552af562471325

**Comment by wschoenell** [comment]
Closing this one. For further discussion about how we resuscitate this plugin, please open another issue.
